title: Danu's homepage
email: danu.pranantha(at)gmail.com
description: >
  the daily life of a software engineer
baseurl: ""
linkedin: danupranantha
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
