# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://dpranantha.github.io
#baseurl:
title: "Engineering Clarity from Complexity"
name: "Danu Pranantha"
description: >- # this means to ignore newlines until "baseurl:"
  Freelance engineer focused on data, ML, and complex systems.
github_username: dpranantha
minimal_mistakes_skin: mint
search: true
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WT7J4Z4YFQ"
    anonymize_ip: false # default
comments:
  provider: "disqus"
  disqus:
    shortname: "dpranantha"
google-site-verification: "m2zCIIMmMyXYxCAMabRxBsHIk0KpWd2Cw_y1f0HC8I8"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
# paginate: 5
# paginate_path: /blog/page:num/
# timezone: Europe/Amsterdam

# Navigation structure
navigation:
  style: dropdowns

header:
  nav:
    dropdowns: true

include:
  - _pages

collections:
  blog:
    output: true
    permalink: /blog/:title/
  books:
    output: true
    permalink: /books/:title/
  posts:
    output: true

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      show_tags: true
      show_categories: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-toc
  - jekyll-remote-theme

author:
  name   : "Danu Pranantha, PhD"
  avatar : "/assets/images/dp.jpeg"
  bio    : "A seasoned engineer bridging software, data, and machine learning."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dpranantha.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dpranantha"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danupranantha/"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=VgqFe_kAAAAJ&hl=nl#"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
